[features]
seeds = true
skip-lint = false
[programs.localnet]
fizzbuzz = "4cFTRddTWosQzVL1rya3pUqkAR8khQRiwQ6L4P11Ze5U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hiro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
